package com.promptpilot.app

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.PixelFormat
import android.graphics.drawable.GradientDrawable
import android.os.Build
import android.os.IBinder
import android.view.Gravity
import android.view.MotionEvent
import android.view.WindowManager
import android.widget.FrameLayout
import android.widget.ImageView
import androidx.core.app.NotificationCompat

/**
 * Foreground Service that draws the PromptPilot floating bubble on screen.
 *
 * Responsibility: manage ONLY the draggable bubble widget via WindowManager.
 * When the user taps the bubble, this service starts FloatingBubbleActivity
 * (a translucent dialog-style Activity) to host the React overlay UI.
 *
 * Why we no longer create a ReactRootView here:
 * --
 * React Native's ReactInstanceManager is lifecycle-coupled to an Activity.
 * Calling startReactApplication() from a Service while the main Activity is
 * backgrounded causes an IllegalStateException crash. The Activity approach
 * eliminates this entirely — the OS handles the window stacking, and the
 * ReactInstanceManager receives proper onHostResume/Pause signals.
 */
class FloatingBubbleService : Service() {

    private lateinit var windowManager: WindowManager
    private var bubbleView: FrameLayout? = null

    private val notificationId = 8899
    private val channelId = "promptpilot_overlay_channel"

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        windowManager = getSystemService(Context.WINDOW_SERVICE) as WindowManager
        createNotificationChannel()
        startForeground(notificationId, createNotification())
        setupBubbleView()
    }

    // ── Notification (required by Foreground Service) ────────────────────────

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                channelId,
                "PromptPilot Overlay Helper",
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = "Displays the PromptPilot floating action bubble."
            }
            (getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager)
                .createNotificationChannel(channel)
        }
    }

    private fun createNotification(): Notification {
        return NotificationCompat.Builder(this, channelId)
            .setContentTitle("PromptPilot Active")
            .setContentText("Tap the floating bubble to open AI quick tools.")
            .setSmallIcon(android.R.drawable.ic_dialog_info)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .build()
    }

    // ── Floating Bubble Widget ───────────────────────────────────────────────

    private fun setupBubbleView() {
        val context = this
        val size = dpToPx(56)

        val frameLayout = FrameLayout(context)
        val params = WindowManager.LayoutParams(
            size,
            size,
            getLayoutType(),
            WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                    WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,
            PixelFormat.TRANSLUCENT
        ).apply {
            gravity = Gravity.TOP or Gravity.START
            x = resources.displayMetrics.widthPixels - size - dpToPx(16)
            y = resources.displayMetrics.heightPixels / 2
        }

        // White circle with subtle border — the app icon fills the interior
        val circle = GradientDrawable().apply {
            shape = GradientDrawable.OVAL
            setColor(Color.WHITE)
            setStroke(dpToPx(1), Color.parseColor("#E5E7EB"))
        }
        frameLayout.background = circle
        frameLayout.elevation = dpToPx(6).toFloat()

        // App launcher icon (generated by expo prebuild from app.json adaptiveIcon)
        val icon = ImageView(context).apply {
            setImageResource(R.mipmap.ic_launcher_round)
            scaleType = ImageView.ScaleType.FIT_CENTER
        }
        val pad = dpToPx(6)
        frameLayout.addView(
            icon,
            FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT,
                FrameLayout.LayoutParams.MATCH_PARENT
            ).also { it.setMargins(pad, pad, pad, pad) }
        )

        // ── Drag + tap mechanics ─────────────────────────────────────────────
        var initialX = 0
        var initialY = 0
        var initialTouchX = 0f
        var initialTouchY = 0f
        var isClick = false

        frameLayout.setOnTouchListener { _, event ->
            when (event.action) {
                MotionEvent.ACTION_DOWN -> {
                    initialX = params.x
                    initialY = params.y
                    initialTouchX = event.rawX
                    initialTouchY = event.rawY
                    isClick = true
                    true
                }
                MotionEvent.ACTION_MOVE -> {
                    val dx = event.rawX - initialTouchX
                    val dy = event.rawY - initialTouchY
                    if (Math.abs(dx) > 10 || Math.abs(dy) > 10) isClick = false
                    params.x = initialX + dx.toInt()
                    params.y = initialY + dy.toInt()
                    windowManager.updateViewLayout(frameLayout, params)
                    true
                }
                MotionEvent.ACTION_UP -> {
                    if (isClick) {
                        // Launch the translucent overlay Activity instead of
                        // mounting a ReactRootView inside this Service.
                        // FLAG_ACTIVITY_NEW_TASK is required when starting an
                        // Activity from a non-Activity context (Service).
                        val intent = Intent(context, FloatingBubbleActivity::class.java).apply {
                            addFlags(
                                Intent.FLAG_ACTIVITY_NEW_TASK or
                                        Intent.FLAG_ACTIVITY_SINGLE_TOP
                            )
                        }
                        startActivity(intent)
                    }
                    true
                }
                else -> false
            }
        }

        bubbleView = frameLayout
        windowManager.addView(frameLayout, params)
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private fun getLayoutType(): Int = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
    } else {
        @Suppress("DEPRECATION")
        WindowManager.LayoutParams.TYPE_PHONE
    }

    private fun dpToPx(dp: Int): Int = (dp * resources.displayMetrics.density).toInt()

    override fun onDestroy() {
        super.onDestroy()
        bubbleView?.let {
            windowManager.removeView(it)
            bubbleView = null
        }
    }
}
